set(_CATKIN_CURRENT_PACKAGE "publish_subscribe")
set(publish_subscribe_VERSION "0.0.0")
set(publish_subscribe_MAINTAINER "hamko <hamko@todo.todo>")
set(publish_subscribe_PACKAGE_FORMAT "1")
set(publish_subscribe_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(publish_subscribe_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(publish_subscribe_BUILDTOOL_DEPENDS "catkin")
set(publish_subscribe_BUILDTOOL_EXPORT_DEPENDS )
set(publish_subscribe_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(publish_subscribe_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(publish_subscribe_TEST_DEPENDS )
set(publish_subscribe_DOC_DEPENDS )
set(publish_subscribe_DEPRECATED "")